services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginxproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-proxy/ssl:/etc/nginx/ssl:ro
      - ./nginx-proxy/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - web1
      - web2
    networks:
      - web

  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./webserver1/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - web

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./webserver2/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - web

networks:
  web:
    driver: bridge
